### PR TITLE
v2 milestone

### PR DESCRIPTION
**Pull request by elmigranto**

### CODE REVIEW

**Comment by elmigranto** [comment]
I've been wondering, what is production env will be. I assume stuff like `Array.forEach()` is pretty reasonable thing to expect it to have, but what about stuff from ES2015, or things like `Object.observe` (`change` for nested objects, yay!)?

**Comment by j3k0** [comment]
Production env is Android >= 3 and iOS >= 6

Unfortunately, `Object.observe` is only available for Android 5+ and not available on iOS.
http://caniuse.com/#feat=object-observe

You can trigger the "change" event manually on your model if you change a nested field... a workaround more than a solution, but better than nothing.

**Comment by elmigranto** [comment]
Okay, fields with non-empty description would either change their name to what it was before, or will add `description -> name` to local storage. I've also added checking for description uniqueness, though it is not quite ideal (it works, but a bit awkward in UX). I think on improving that alongside #11 to not do same work twice.

I believe everything else must be in place for v2, sorry for delaying it.

**Comment by j3k0** [comment]
Great, if all v2.0 issues are done. Let's merge this in, and proceed in a v2.1 branch.

**Comment by elmigranto** [comment]
Let's merge.

**Pull request merged**
