### PR TITLE
Dynamic Fields (Issue #1)

### PR DESCRIPTION
**Pull request by elmigranto**

### CODE REVIEW

**Comment by j3k0** [comment]
Seems alright. doing `npm install` fails here so I can't run the test. What version of node are you using? Also from package.json, think backbone isn't a **dev** dependency but a runtime dep.

Concerning code, good start. Although creating a new procedure shouldn't fill any value, just empty string. The date should be in format : "dd-mm-yyyy HH:MM" (day-month-year hour:minutes)

Except from that, good first step!

**Comment by elmigranto** [comment]
> `npm install` fails

``` sh
$ node -v && npm -v
v0.12.7
2.14.1
```

Okay, thanks for feedback.

**Comment by j3k0** [comment]
thanks, had to upgrade npm from 2.13 to 2.14

**Comment by j3k0** [comment]
BTW, while reading though the code I realized my spec has a little mistake: in the 3 "required" field, `name` should have been `patient`.

**Comment by elmigranto** [comment]
Trying to sort what is up with ordering, please look through latest commit — I'm adding some line comments, and would like to hear what you think.

(That's not final, just pushed it for discussion, will amend.)

**Comment by elmigranto** [comment]
Okay, this looks like something that is somewhat complete functionality-wise as discussed in #1.

Though there are almost no sanity checks, validations, or error handling of any sort, I'd like you to make sure whether I got core concepts right. After your approval, I'll go refactor some stuff, add missing parts and make it more final-product-like.

**Comment by j3k0** [comment]
Okay, will look into it right now.

**Comment by j3k0** [comment]
Hey. You got it right! :+1: 

I got a crash when trying to edit an optional choicetree, don't know if you know about this one.

A few small functional things:
- I don't think it's necessary to edit the name of the template's optional field, editing the description only is enough (well, we can just hide the input).
- would be nice that if the combo of the template's fields' type selector can be some plain english (or french, i'll do the translation later)
- I think the template editor should either:
  - have a single "save" button
  - show the fields read-only + a "edit" button that turns them editable. once editable, "save changes" will make them read-only again.

That's all. Good job so far!

Just to let you know where you're going: next step would be to add pagination to the list of procedures (N per page) and a "Search" input, that'll filter by patient names. Maybe later some more advanced search (but unsure yet).

**Comment by elmigranto** [comment]
> would be nice that if the combo of the template's fields' type selector can be some plain english

You mean instead of `CHOICETREE` add some "normal" words?

> I got a crash when trying to edit an optional choicetree

When you click on choictree, it calls `openChoiceTree(name)` where name is `field.name`. It fails because there are no ChoiceTree for that field, that is something I was planning to do after.

> have a single "save" button
> show the fields read-only + a "edit" button

Yep, that's something for later too. Maybe we can even listen to inputs' change event, no buttons at all!

**Comment by j3k0** [comment]
> You mean instead of CHOICETREE add some normal words?

Yes.

> Maybe we can even listen to inputs' change event, no buttons at all!

That's good as well!

**Comment by elmigranto** [comment]
Okay, most stuff looks good enough to me and working without major issues. What is "left":
- A bit inconsistent TreePickerView rendering, would like to inspect it deeper, but this is kind of non-related thing that works for now!
- Photo input that is kinda there but non-operational for now, what would you like to be done about it?
- `alert()`, general structure refactor (like `ProcedureModel#diff()` could be in every model, so why not make our own `Backbone.extend`/`BaseModel` version) and other mostly unrelated possible improvements…

Anyways, there are a lot of stuff that can be done, but #1-related things are in place, and I think this PR is in a good enough state for that. Please review and let me know what you think.

**Comment by j3k0** [comment]
I tested the app, but didn't read through the code yet. Is it possible to easily hide all the debug shown in the HTML?

Encountered a few issues:
- In the template editor: `add new field` will add 2 fields instead of 1. (on Chrome 45)
- For newly added `choicetree` fields, the TreePicker will show `Custom Tree?` as a title (on the root node of the tree). It would be nice to show the field description here.
- Photos are missing, I'll create a separate issue to discuss this.

For a few extra improvements, I'll also make separate issues. Reading through the code now.

**Comment by elmigranto** [comment]
> `add new field` will add 2 fields instead of 1

**Comment by elmigranto** [comment]
Okay, do we merge this or keep adding stuff from #4 and #5?

**Comment by j3k0** [comment]
I'd rather merge: it's easier for code review.

**Comment by elmigranto** [comment]
Okay then.

**Pull request merged**
